"""
SQLAlchemy ORM models for the database schema.
"""

from datetime import datetime
from sqlalchemy import (
    Boolean, Column, Integer, String, Text, DateTime, ForeignKey,
    Enum, Float, UniqueConstraint, JSON, func, Index
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import text
import enum

from src.common.database.connection import Base


##### ENUMS #####

# Common 
class JobStatusEnum(enum.Enum):
    """Status of a generic job."""
    running = "running"
    completed = "completed"
    failed = "failed"
    paused = "paused" # For QAJob

# Scoring
class StatusEnum(enum.Enum):
    """Status for personas and questions."""
    pending = "pending"
    approved = "approved"
    rejected = "rejected"
    edited = "edited"

class JobTypeEnum(enum.Enum):
    """Type of generation job."""
    persona_generation = "persona_generation"
    question_generation = "question_generation"

class QuestionTypeEnum(enum.Enum):
    """Type of question."""
    typical = "typical"  # Typical use case questions
    edge = "edge"  # Edge case questions

class QuestionScopeEnum(enum.Enum):
    """Scope of question relative to knowledge base."""
    in_kb = "in_kb"  # Question about content within the knowledge base
    out_kb = "out_kb"  # Question about content outside the knowledge base

class InputStyleEnum(enum.Enum):
    """Input style for questions."""
    brief = "brief"
    regular = "regular"
    detailed = "detailed"

class QuestionSourceEnum(enum.Enum):
    """Source of question creation."""
    job_generated = "job_generated"  # Generated by a job
    uploaded = "uploaded"  # Uploaded via bulk import

class PersonaSourceEnum(enum.Enum):
    """Source of persona creation."""
    generated = "generated"  # Generated by LLM via a job
    nemotron = "nemotron"  # Sampled from Nemotron dataset


# Scoring
class QAJobTypeEnum(enum.Enum):
    """Type of generation job."""
    claim_scoring_full = "claim_scoring_full" # Handles answer generation -> process claims -> judge claims
    response_scoring_full = "response_scoring_full" # Handles answer generation -> judge answers
    claim_scoring_only = "claim_scoring_only" # Handles read claims -> judge claims
    response_scoring_only = "response_scoring_only" # Handles read answers -> judge claims

class QAJobStageEnum(enum.Enum):
    """Stages of a QAJob"""
    starting = "starting"
    generating_answers = "generating_answers"
    processing_answers = "processing_answers" # Any type of answer processing, e.g. extracting claims, or processing full responses
    scoring_answers = "scoring_answers" # Any type of answer scoring, e.g. claim scoring or response scoring
    completed = "completed" # Any type of answer scoring, e.g. claim scoring or response scoring

class JudgeTypeEnum(enum.Enum):
    """Type of judge evaluation."""
    claim_based = "claim_based"  # Evaluates claims individually, then aggregates
    response_level = "response_level"  # Evaluates entire response holistically


##### AUTH #####

class User(Base):
    """User for authentication."""
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, nullable=False, index=True)
    hashed_password = Column(String, nullable=False)
    is_active = Column(Boolean, default=True, nullable=False)
    is_admin = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    targets = relationship("Target", back_populates="owner")
    judges = relationship("Judge", back_populates="owner")

    def __repr__(self):
        return f"<User(id={self.id}, username='{self.username}', is_admin={self.is_admin})>"


##### GENERAL #####

class Target(Base):
    """Target application for evaluation."""
    __tablename__ = "targets"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True)
    name = Column(String, nullable=False, index=True)
    agency = Column(String, nullable=True)
    purpose = Column(Text, nullable=True)
    target_users = Column(Text, nullable=True)
    api_endpoint = Column(String, nullable=True)
    endpoint_type = Column(String, nullable=True)  # "aibots", "custom_api", etc.
    endpoint_config = Column(JSON, nullable=True)  # Type-specific config
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    owner = relationship("User", back_populates="targets")
    jobs = relationship("Job", back_populates="target", cascade="all, delete-orphan")
    personas = relationship("Persona", back_populates="target", cascade="all, delete-orphan")
    questions = relationship("Question", back_populates="target", cascade="all, delete-orphan")
    kb_documents = relationship("KnowledgeBaseDocument", back_populates="target", cascade="all, delete-orphan")
    web_documents = relationship("WebDocument", back_populates="target", cascade="all, delete-orphan")
    snapshots = relationship("Snapshot", back_populates="target", cascade="all, delete-orphan")
    custom_rubrics = relationship("TargetRubric", back_populates="target", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Target(id={self.id}, name='{self.name}', user_id={self.user_id})>"


##### QUERY GENERATION #####

class Job(Base):
    """Generation job for personas or questions."""
    __tablename__ = "jobs"

    id = Column(Integer, primary_key=True, index=True)
    target_id = Column(Integer, ForeignKey("targets.id", ondelete="CASCADE"), nullable=False, index=True)
    type = Column(Enum(JobTypeEnum), nullable=False, index=True)
    persona_id = Column(Integer, ForeignKey("personas.id", ondelete="SET NULL"), nullable=True, index=True)
    count_requested = Column(Integer, nullable=False)
    model_used = Column(String, nullable=False)
    generation_prompt = Column(Text, nullable=True)
    status = Column(Enum(JobStatusEnum), default=JobStatusEnum.running, nullable=False, index=True)
    prompt_tokens = Column(Integer, default=0)
    completion_tokens = Column(Integer, default=0)
    total_cost = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    target = relationship("Target", back_populates="jobs")
    persona = relationship("Persona", foreign_keys=[persona_id])
    personas_generated = relationship("Persona", back_populates="job", foreign_keys="Persona.job_id")
    questions_generated = relationship("Question", back_populates="job")

    def __repr__(self):
        return f"<Job(id={self.id}, type={self.type.value}, status={self.status.value}, cost=${self.total_cost:.4f})>"


class Persona(Base):
    """Generated or sampled persona for a target application."""
    __tablename__ = "personas"

    id = Column(Integer, primary_key=True, index=True)
    source = Column(Enum(PersonaSourceEnum), default=PersonaSourceEnum.generated, nullable=False, index=True)
    job_id = Column(Integer, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=True, index=True)  # Required if source=generated, else NULL
    target_id = Column(Integer, ForeignKey("targets.id", ondelete="CASCADE"), nullable=False, index=True)
    title = Column(String, nullable=False)
    info = Column(Text, nullable=True)
    style = Column(Text, nullable=True)
    use_case = Column(Text, nullable=True)
    status = Column(Enum(StatusEnum), default=StatusEnum.pending, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    job = relationship("Job", back_populates="personas_generated", foreign_keys=[job_id])
    target = relationship("Target", back_populates="personas")
    questions = relationship("Question", back_populates="persona", cascade="all, delete-orphan")

    # Unique constraint: title must be unique per target
    __table_args__ = (
        UniqueConstraint('target_id', 'title', name='uix_target_persona_title'),
    )

    def __repr__(self):
        return f"<Persona(id={self.id}, title='{self.title}', status={self.status.value})>"


class Question(Base):
    """Generated or uploaded question for a persona."""
    __tablename__ = "questions"

    id = Column(Integer, primary_key=True, index=True)
    source = Column(Enum(QuestionSourceEnum), default=QuestionSourceEnum.job_generated, nullable=False, index=True)
    job_id = Column(Integer, ForeignKey("jobs.id", ondelete="CASCADE"), nullable=True, index=True)  # Required if source=job_generated, else NULL
    persona_id = Column(Integer, ForeignKey("personas.id", ondelete="CASCADE"), nullable=True, index=True)  # Required if source=job_generated, else optional
    target_id = Column(Integer, ForeignKey("targets.id", ondelete="CASCADE"), nullable=False, index=True)
    orig_id = Column(String, nullable=True, index=True)  # Original ID from user's file (for uploaded questions)
    text = Column(Text, nullable=False)
    type = Column(Enum(QuestionTypeEnum), nullable=True, index=True)  # typical or edge; nullable for uploaded questions
    scope = Column(Enum(QuestionScopeEnum), nullable=True, index=True)  # in_kb or out_kb; nullable for uploaded questions
    input_style = Column(Enum(InputStyleEnum), nullable=True)  # brief, regular, detailed
    status = Column(Enum(StatusEnum), default=StatusEnum.pending, nullable=False, index=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    job = relationship("Job", back_populates="questions_generated")
    persona = relationship("Persona", back_populates="questions")
    target = relationship("Target", back_populates="questions")
    answers = relationship("Answer", back_populates="question", cascade="all, delete-orphan")
    qa_jobs = relationship("QAJob", back_populates="question", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Question(id={self.id}, persona_id={self.persona_id}, type={self.type.value}, scope={self.scope.value}, status={self.status.value})>"


class Answer(Base):
    """Generated answer from AIBots API for a question."""
    __tablename__ = "answers"

    id = Column(Integer, primary_key=True, index=True)
    question_id = Column(Integer, ForeignKey("questions.id", ondelete="CASCADE"), nullable=False, index=True)
    snapshot_id = Column(Integer, ForeignKey("snapshots.id", ondelete="CASCADE"), nullable=False, index=True)

    # AIBots identifiers
    chat_id = Column(String, nullable=True)
    message_id = Column(String, nullable=True)

    # Important fields (extracted for easy querying)
    answer_content = Column(Text, nullable=False)
    system_prompt = Column(Text, nullable=True)
    model = Column(String, nullable=True)
    guardrails = Column(JSON, nullable=True)
    rag_citations = Column(JSON, nullable=True)

    # Full raw response for traceability
    raw_response = Column(JSON, nullable=True)

    # Annotation selection
    is_selected_for_annotation = Column(Boolean, default=False, nullable=False, index=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    qa_jobs = relationship("QAJob", back_populates="answer", cascade="all, delete")
    snapshot = relationship("Snapshot", back_populates="answers")
    question = relationship("Question", back_populates="answers")
    claims = relationship("AnswerClaim", back_populates="answer", cascade="all, delete-orphan")
    scores = relationship("AnswerScore", back_populates="answer", cascade="all, delete-orphan")
    rubric_answer_scores = relationship("RubricAnswerScore", back_populates="answer", cascade="all, delete-orphan")
    rubric_annotations = relationship("RubricAnnotation", back_populates="answer", cascade="all, delete-orphan")
    annotation = relationship("Annotation", back_populates="answer", uselist=False, cascade="all, delete-orphan")

    # Unique constraint: one answer per question per snapshot
    __table_args__ = (
        UniqueConstraint('question_id', 'snapshot_id', name='uix_question_snapshot_answer'),
    )

    def __repr__(self):
        return f"<Answer(id={self.id}, question_id={self.question_id}, snapshot_id={self.snapshot_id})>"


class KnowledgeBaseDocument(Base):
    """Knowledge base document for a target."""
    __tablename__ = "knowledge_base_documents"

    id = Column(Integer, primary_key=True, index=True)
    target_id = Column(Integer, ForeignKey("targets.id", ondelete="CASCADE"), nullable=False, index=True)
    filename = Column(String, nullable=False)
    content_type = Column(String, nullable=False)  # "application/pdf", "text/plain", etc
    processed_text = Column(Text, nullable=False)  # Full extracted and cleaned text
    file_size = Column(Integer, nullable=False)  # Size in bytes
    page_count = Column(Integer, nullable=True)  # For PDFs/DOCX
    sequence_order = Column(Integer, default=0)  # For ordering multiple docs
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    target = relationship("Target", back_populates="kb_documents")

    def __repr__(self):
        return f"<KnowledgeBaseDocument(id={self.id}, target_id={self.target_id}, filename='{self.filename}')>"


class WebDocument(Base):
    """Web search results document for a target.

    Each row represents one web search service call (containing multiple search results).
    """
    __tablename__ = "web_documents"

    id = Column(Integer, primary_key=True, index=True)
    target_id = Column(Integer, ForeignKey("targets.id", ondelete="CASCADE"), nullable=False, index=True)
    search_queries = Column(JSON, nullable=False)  # List of query strings used
    results = Column(JSON, nullable=False)  # SearchResultsOutput as dict
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    # Relationships
    target = relationship("Target", back_populates="web_documents")

    def __repr__(self):
        return f"<WebDocument(id={self.id}, target_id={self.target_id})>"


##### SCORING #####

class Snapshot(Base):
    """Snapshots for a target."""
    __tablename__ = "snapshots"

    # PK
    id = Column(Integer, primary_key=True, index=True)
    # FK
    target_id = Column(Integer, ForeignKey("targets.id", ondelete="CASCADE"), nullable=False, index=True)

    # Fields
    name = Column(String, nullable=False)
    description = Column(String, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    target = relationship("Target", back_populates="snapshots")
    answers = relationship("Answer", back_populates="snapshot", cascade="all, delete-orphan")
    qa_jobs = relationship("QAJob", back_populates="snapshot", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Snapshot(id={self.id}, target_id={self.target_id}, name='{self.name}')>"

class QAJob(Base):
    """QA job for the scoring pipeline for 1 question - answer pair."""
    __tablename__ = "qa_jobs"

    # PK
    id = Column(Integer, primary_key=True, index=True)
    # FK
    snapshot_id = Column(Integer, ForeignKey("snapshots.id", ondelete="CASCADE"), nullable=False, index=True)
    question_id = Column(Integer, ForeignKey("questions.id", ondelete="CASCADE"), nullable=False, index=True)
    judge_id = Column(Integer, ForeignKey("judges.id", ondelete="CASCADE"), nullable=True, index=True)
    answer_id = Column(Integer, ForeignKey("answers.id", ondelete="SET NULL"), nullable=True, index=True)

    # Fields
    rubric_specs = Column(JSON, nullable=True)  # [{"rubric_id": int, "judge_id": int}, ...]
    type = Column(Enum(QAJobTypeEnum), nullable=False, index=True)
    status = Column(Enum(JobStatusEnum), default=JobStatusEnum.running, nullable=False, index=True)
    stage = Column(Enum(QAJobStageEnum), default=QAJobStageEnum.starting, nullable=False, index=True)
    error_message = Column(Text, nullable=True)  # Stores error details when job fails
    prompt_tokens = Column(Integer, default=0)
    completion_tokens = Column(Integer, default=0)
    total_cost = Column(Float, default=0.0)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    snapshot = relationship("Snapshot", back_populates="qa_jobs")
    question = relationship("Question", back_populates="qa_jobs")
    answer = relationship("Answer", back_populates="qa_jobs")
    judge = relationship("Judge", back_populates="qa_jobs")

    __table_args__ = (
        Index('uix_snapshot_question', 'snapshot_id', 'question_id', unique=True),
    )

    def __repr__(self):
        return f"<QAJob(id={self.id}, type={self.type.value}, status={self.status.value}, stage={self.stage.value})>"


class Judge(Base):
    """Judges for the scoring pipeline."""
    __tablename__ = "judges"

    # PK
    id = Column(Integer, primary_key=True, index=True)
    # FK
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True)
    target_id = Column(Integer, ForeignKey("targets.id", ondelete="CASCADE"), nullable=True, index=True)

    # Fields
    name = Column(String, nullable=False)
    model_name = Column(String, nullable=False)
    model_label = Column(String, nullable=True)
    prompt_template = Column(Text, nullable=False)
    params = Column(JSON, nullable=False, default=dict)
    judge_type = Column(Enum(JudgeTypeEnum), nullable=False)
    is_baseline = Column(Boolean, default=False, nullable=False)
    is_editable = Column(Boolean, default=True, nullable=False)
    category = Column(String, nullable=False, default="accuracy")
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    owner = relationship("User", back_populates="judges")
    target = relationship("Target", foreign_keys=[target_id])
    qa_jobs = relationship("QAJob", back_populates="judge", passive_deletes=True)
    answer_scores = relationship("AnswerScore", back_populates="judge", passive_deletes=True)
    rubric_answer_scores = relationship("RubricAnswerScore", back_populates="judge", passive_deletes=True)



class AnswerClaim(Base):
    """
    A single claim extracted from an answer.
    """
    __tablename__ = "answer_claims"

    # PK
    id = Column(Integer, primary_key=True, index=True)
    # FK
    answer_id = Column(Integer, ForeignKey("answers.id", ondelete="CASCADE"), nullable=False, index=True)

    # Fields
    claim_index = Column(Integer, nullable=False) # position of this claim within the answer (0, 1, 2, …)
    claim_text = Column(Text, nullable=False)
    checkworthy = Column(Boolean, nullable=False)  # True = worth scoring, False = not worth scoring

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    checked_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    answer = relationship("Answer", back_populates="claims")
    claim_scores = relationship("AnswerClaimScore", back_populates="claim", cascade="all, delete-orphan")


class AnswerClaimScore(Base):
    """
    Score for a *single claim*, usually tied to an answer-level score / judge.
    """
    __tablename__ = "answer_claim_scores"

    # PK
    id = Column(Integer, primary_key=True, index=True)
    # FK
    claim_id = Column(Integer, ForeignKey("answer_claims.id", ondelete="CASCADE"), nullable=False)
    answer_score_id = Column(Integer, ForeignKey("answer_scores.id", ondelete="CASCADE"), nullable=False)

    # Fields
    label = Column(Boolean, nullable=False)  # True = Accurate, False = Inaccurate (Hallucinated)
    explanation = Column(Text, nullable=False)  # Why claim is/isn't supported by KB\
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    
    # Relationships
    claim = relationship("AnswerClaim", back_populates="claim_scores")
    answer_score = relationship("AnswerScore", back_populates="claim_scores")


class AnswerScore(Base):
    """
    One row per (answer, judge) pair:
    - aggregate score at answer level
    - can optionally be broken down into claim-level scores
    """
    __tablename__ = "answer_scores"

    # PK
    id = Column(Integer, primary_key=True, index=True)
    # FK
    answer_id = Column(Integer, ForeignKey("answers.id", ondelete="CASCADE"), nullable=True)
    judge_id = Column(Integer, ForeignKey("judges.id", ondelete="CASCADE"), nullable=True)

    # Fields
    overall_label = Column(Boolean, nullable=False)  # True = Accurate, False = Inaccurate (Hallucinated)
    explanation = Column(Text, nullable=True)  # Aggregated explanation
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    answer = relationship("Answer", back_populates="scores")
    judge = relationship("Judge", back_populates="answer_scores")
    claim_scores = relationship("AnswerClaimScore", back_populates="answer_score", cascade="all, delete-orphan")

    __table_args__ = (
        UniqueConstraint("answer_id", "judge_id", name="uix_answer_judge_score"),
    )

class Annotation(Base):
    """
    Human annotation at answer level.
    """
    __tablename__ = "annotations"

    id = Column(Integer, primary_key=True, index=True)

    answer_id = Column(Integer, ForeignKey("answers.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    # if you have annotators / annotation sets, add FKs here:
    # annotation_set_id = Column(Integer, ForeignKey("annotation_sets.id"), nullable=False)
    # annotator_id = Column(Integer, ForeignKey("annotators.id"), nullable=True)

    label = Column(Boolean, nullable=False)  # True = Accurate, False = Inaccurate
    notes = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    answer = relationship("Answer", back_populates="annotation")


class AnswerLabelOverride(Base):
    """
    User override for aggregated accuracy label at answer level.
    Allows users to manually correct the majority-vote label.
    """
    __tablename__ = "answer_label_overrides"

    id = Column(Integer, primary_key=True, index=True)
    answer_id = Column(Integer, ForeignKey("answers.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    metric_name = Column(String(50), nullable=False, default="accuracy")
    edited_label = Column(Boolean, nullable=False)  # True = Accurate, False = Inaccurate
    edited_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    answer = relationship("Answer")


class TargetRubric(Base):
    """Custom evaluation rubric for a target."""
    __tablename__ = "target_rubrics"

    id = Column(Integer, primary_key=True, index=True)
    target_id = Column(Integer, ForeignKey("targets.id", ondelete="CASCADE"), nullable=False, index=True)
    name = Column(String, nullable=False)
    criteria = Column(Text, nullable=False, default="")
    options = Column(JSON, nullable=False, default=list)
    position = Column(Integer, nullable=False, default=0)
    category = Column(String, nullable=False, default="default")  # legacy, no longer written to
    best_option = Column(String, nullable=True)  # user-specified positive option for scoring
    judge_prompt = Column(Text, nullable=True)  # complete judge prompt for this rubric
    template_key = Column(String, nullable=True)  # pre-made template identifier (e.g. "empathy"), null for custom
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    target = relationship("Target", back_populates="custom_rubrics")
    rubric_annotations = relationship("RubricAnnotation", back_populates="rubric", cascade="all, delete-orphan")
    rubric_answer_scores = relationship("RubricAnswerScore", back_populates="rubric", cascade="all, delete-orphan")


class RubricAnnotation(Base):
    """Per-rubric human annotation for a single answer."""
    __tablename__ = "rubric_annotations"

    id = Column(Integer, primary_key=True, index=True)
    answer_id = Column(Integer, ForeignKey("answers.id", ondelete="CASCADE"), nullable=False, index=True)
    rubric_id = Column(Integer, ForeignKey("target_rubrics.id", ondelete="CASCADE"), nullable=False, index=True)
    option_value = Column(String, nullable=False)  # The selected option text
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    __table_args__ = (
        UniqueConstraint("answer_id", "rubric_id", name="uix_rubric_annotation"),
    )

    # Relationships
    answer = relationship("Answer", back_populates="rubric_annotations")
    rubric = relationship("TargetRubric", back_populates="rubric_annotations")

    def __repr__(self):
        return f"<RubricAnnotation(id={self.id}, answer_id={self.answer_id}, rubric_id={self.rubric_id})>"


class RubricAnswerScore(Base):
    """LLM judge score for a custom rubric on a single answer."""
    __tablename__ = "rubric_answer_scores"

    id = Column(Integer, primary_key=True, index=True)
    answer_id = Column(Integer, ForeignKey("answers.id", ondelete="CASCADE"), nullable=False, index=True)
    rubric_id = Column(Integer, ForeignKey("target_rubrics.id", ondelete="CASCADE"), nullable=False, index=True)
    judge_id = Column(Integer, ForeignKey("judges.id", ondelete="CASCADE"), nullable=False, index=True)
    option_chosen = Column(String, nullable=False)
    explanation = Column(Text, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    __table_args__ = (
        UniqueConstraint("answer_id", "rubric_id", "judge_id", name="uix_answer_rubric_judge_score"),
    )

    # Relationships
    answer = relationship("Answer", back_populates="rubric_answer_scores")
    rubric = relationship("TargetRubric", back_populates="rubric_answer_scores")
    judge = relationship("Judge", back_populates="rubric_answer_scores")

    def __repr__(self):
        return f"<RubricAnswerScore(id={self.id}, answer_id={self.answer_id}, rubric_id={self.rubric_id})>"
